### ISSUE TITLE
 React.PropTypes is undefined

### ISSUE THREAD

**Issue by taronarm** [fukuball/react-native-orientation-loading-overlay#1]
You used React.PropTypes to define types of params, but **PropTypes** already **removed from React core**. As result error throws on package import.
Separate package **prop-types** need to be installed/imported and used for prop types checking:

```
static propTypes = {
    visible: PropTypes.bool,
    color: PropTypes.string,
    indicatorSize: PropTypes.oneOf(SIZES),
    messageFontSize: PropTypes.number,
    message: PropTypes.string
};
```

or trust developers and remove prop types checking totally ;)

**Comment by fukuball** [comment]
@TaronSaribekyan Thank, I'll update this.

**Comment by fukuball** [comment]
I choose to trust developers and remove prop types checking to fix this issue~
